### ISSUE TITLE
Subscribe Buttons Broken?

### ISSUE THREAD

**Issue by toddgrotenhuis** [endonend/Hains-Point#10]
I noticed I could not subscribe either on the top button or side button on my site. But I can subscribe on the normal subscribe form page (/subscribe/). I wondered if I broke something or entered my subscribe number wrong.

But then I went and tested on your blog and the buttons did nothing for me there, either.

(granted, could be something my browser is blocking, but the normal subscribe page button is working)

**Comment by endonend** [comment]
Strange! I justed tested a new email on my site (both locations) and got the right message:

> An email has been sent to jason@ekowave.com to confirm your subscription.
> 
>  Profile icon[ Back to endonend.micro.blog](https://endonend.micro.blog/)

What browser are you using?

Edit: I am using Safari on MacOS 12.3

**Comment by toddgrotenhuis** [comment]
Vivaldi.

I turned off uBlock Origin and it works. Looks like one of the calls to sentry.io or plausible analytics getting blocked is what is blocking the subscribe action.

**Comment by toddgrotenhuis** [comment]
Looks like it's these calls: https://o374023.ingest.sentry.io/api/...

**Comment by endonend** [comment]
I did add the Plausible tracking to the button for those forms. I will do some more testing... might be worth reverting that, if it's going to cause issues. Thanks for the report!

**Comment by toddgrotenhuis** [comment]
> Looks like it's these calls: https://o374023.ingest.sentry.io/api/...

I'm wrong...this happens on the /subscribe/ page too and that goes through ok.

**Comment by toddgrotenhuis** [comment]
I may have something else blocking the action (nextdns, etc.) let me debug the difference further between /subscribe/ and the subscribe buttons.

**Comment by toddgrotenhuis** [comment]
I am not 100% certain, but it does appear to be plausible analytics. (I admit/realize using PA might be a required feature for some users.)

**Comment by endonend** [comment]
I will see if I can make it optional at the very least. Thanks for the research!

**Comment by endonend** [comment]
OK, I removed the button tracking code from my site. Could you test your setup to see if that's the culprit?

[endonend.micro.blog](https://endonend.micro.blog)

If it is, I will see what I can do about making it optional and if not, remove it all together. With the rise in privacy/blocking tech, I think it makes sense to go that route, if it is indeed the problem.

Thanks!

**Comment by toddgrotenhuis** [comment]
Submitted an email address successfully! That was it.

**Comment by endonend** [comment]
OK cool, thanks for the debug help! Will see what I can do...

**Comment by endonend** [comment]
Added a toggle for this in 2022.1.9, which I just checked in...
