### ISSUE TITLE
Two places for Footer Text Color

### ISSUE THREAD

**Issue by toddgrotenhuis** [endonend/Hains-Point#6]
What is the difference, or does one override the other?

<img width="220" alt="image" src="https://user-images.githubusercontent.com/165077/157350852-e0757837-367e-4821-af45-27d129effc1d.png">

**Comment by toddgrotenhuis** [comment]
(see top and bottom entry in screenshot)

**Comment by endonend** [comment]
Good catch. I couldn't get the header text color to work consistently so I dropped that and added a footer option instead. Will remove the header text reference.

**Comment by endonend** [comment]
Good catch! Actually a copy and paste error -- the top one is the wide subscribe box text color. Will fix in the next update.

**Comment by endonend** [comment]
This will be fixed in the next release.
